-- Create gsec table
-- Note: This is a comprehensive table for government securities transactions
CREATE TABLE IF NOT EXISTS gsec (
  id INT AUTO_INCREMENT PRIMARY KEY,
  deal_number VARCHAR(50) UNIQUE NOT NULL,
  transaction_type ENUM('Buy', 'Sell') NOT NULL,
  counterparty_id INT NOT NULL,
  isin_number VARCHAR(50) NOT NULL,
  face_value DECIMAL(20,4) NOT NULL,
  value_date DATE NOT NULL,
  next_coupon_date DATE,
  last_coupon_date DATE,
  number_of_days_interest_accrued INT,
  number_of_days_for_coupon_period INT,
  accrued_interest DECIMAL(20,6),
  accrued_interest_base DECIMAL(20,6),
  coupon_interest DECIMAL(20,6),
  clean_price DECIMAL(20,6),
  dirty_price DECIMAL(20,6),
  coupon_date_1 DATE,
  coupon_date_2 DATE,
  issue_date DATE,
  maturity_date DATE,
  coupon_rate DECIMAL(10,4),
  yield_rate DECIMAL(10,4),
  clean_price_base DECIMAL(20,6),
  accrued_interest_calculation VARCHAR(50),
  broker_id INT,
  accrued_interest_six_decimals DECIMAL(20,6),
  accrued_interest_for_100 DECIMAL(20,6),
  settlement_amount DECIMAL(20,4),
  settlement_mode VARCHAR(50),
  coupon_dates TEXT,
  yield DECIMAL(10,4),
  brokerage DECIMAL(20,6),
  currency VARCHAR(10) DEFAULT 'LKR',
  portfolio VARCHAR(255),
  strategy VARCHAR(255),
  broker VARCHAR(255),
  accrued_interest_adjustment DECIMAL(20,6) DEFAULT 0,
  clean_price_adjustment DECIMAL(20,6) DEFAULT 0,
  trade_date DATE,
  buy_deal_number VARCHAR(50),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_deal_number (deal_number),
  INDEX idx_isin (isin_number),
  INDEX idx_counterparty (counterparty_id),
  INDEX idx_value_date (value_date),
  INDEX idx_maturity_date (maturity_date),
  INDEX idx_buy_deal_number (buy_deal_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
